name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 75fc63d5-847c-4983-866d-25466b1eaa1d
        tenant-id: 3f0f658d-adb1-4332-a066-75915f54a811
        subscription-id: 885be1e7-1990-4e52-a221-841382209984
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.17
      with:
        app-name: anderson-test-10
        package: .
        startup-command: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'